CREATE TABLE ESTADOS (
	est_id NUMBER(6),
	est_uf VARCHAR2(2),
	est_nome VARCHAR2(15),

	CONSTRAINT PK_ESTADOS PRIMARY KEY (est_id)
);

CREATE TABLE CIDADES (
	cid_id NUMBER(6),
	cid_nome VARCHAR2(30),
	cid_est_id NUMBER(6),

	CONSTRAINT PK_CIDADES PRIMARY KEY (cid_id),
	CONSTRAINT FK_CID_EST FOREIGN KEY (cid_est_id) REFERENCES ESTADOS (est_id)
);

CREATE TABLE ENDERECOS (
	end_id NUMBER(6),
	end_logradouro VARCHAR2(255),
	end_numero VARCHAR2(6),
	end_cep VARCHAR2(8),
	end_bairro VARCHAR2(255),
	end_cid_id NUMBER(6),

	CONSTRAINT PK_ENDERECOS PRIMARY KEY (end_id),
	CONSTRAINT FK_END_CID FOREIGN KEY (end_cid_id) REFERENCES CIDADES (cid_id)
);

CREATE TABLE USUARIOS (
	usu_id NUMBER(6),
	usu_pnome VARCHAR2(30),
	usu_snome VARCHAR2(30),
	usu_unome VARCHAR2(30),
	usu_dt_nasc DATE,
	usu_telefone VARCHAR2(11),
	usu_cpf VARCHAR2(15),
	usu_email VARCHAR2(65),
	usu_end_id NUMBER(6),

	CONSTRAINT PK_USUARIOS PRIMARY KEY (usu_id),
	CONSTRAINT FK_USU_END FOREIGN KEY (usu_end_id) REFERENCES ENDERECOS (end_id)
);

CREATE TABLE CONVERSAS (
	cnv_id NUMBER(6),
	cnv_sol_id NUMBER(6),
	cnv_dns_id NUMBER(6),

	CONSTRAINT PK_CONVERSAS PRIMARY KEY (cnv_id),
	CONSTRAINT FK_CNV_DNS FOREIGN KEY (cnv_dns_id) REFERENCES USUARIOS (usu_id),
	CONSTRAINT FK_CNV_SOL FOREIGN KEY (cnv_sol_id) REFERENCES USUARIOS (usu_id)
);

CREATE TABLE MENSAGENS (
	msg_id NUMBER(6),
	msg_data DATE,
	msg_conteudo CLOB,
	msg_cnv_id NUMBER(6),

	CONSTRAINT PK_MENSAGENS PRIMARY KEY (msg_id),
	CONSTRAINT FK_MSG_CNV FOREIGN KEY (msg_cnv_id) REFERENCES CONVERSAS (cnv_id)
);

CREATE TABLE PRODUTOS (
	prd_id NUMBER(6), 
	prd_nome VARCHAR2(30), 
	prd_consumo SMALLINT, 
	prd_material VARCHAR2(15),
	prd_peso NUMBER(6, 2),

	CONSTRAINT PK_PRODUTOS PRIMARY KEY (prd_id)
);

CREATE TABLE EXEMPLARES (
	exp_id NUMBER(6),
	exp_prd_id NUMBER(6),
	exp_usu_id NUMBER(6),

	CONSTRAINT PK_EXEMPLARES PRIMARY KEY (exp_id),
	CONSTRAINT FK_EXP_PRD FOREIGN KEY (exp_prd_id) REFERENCES PRODUTOS (prd_id),
	CONSTRAINT FK_USU_PRD FOREIGN KEY (exp_usu_id) REFERENCES USUARIOS (usu_id)
);

CREATE TABLE TIPOS_PRODUTO (
	tpd_id NUMBER(6),
	tpd_descricao VARCHAR2(10),
	tpd_peso NUMBER(6, 2),

	CONSTRAINT PK_TIPOS_PRODUTO PRIMARY KEY (tpd_id)
);

CREATE TABLE PRODUTOS_TIPOS_PRODUTO (
	ptp_id NUMBER(6),
	ptp_prd_id NUMBER(6), 
	ptp_tpd_id NUMBER(6),

	CONSTRAINT PK_PRODUTOS_TIPOS_PRODUTO PRIMARY KEY (ptp_id),
	CONSTRAINT FK_PTP_PRD FOREIGN KEY (ptp_prd_id) REFERENCES PRODUTOS (prd_id),
	CONSTRAINT FK_PTP_TPD FOREIGN KEY (ptp_tpd_id) REFERENCES TIPOS_PRODUTO (tpd_id)
);

CREATE TABLE PREFERENCIAS (
	prf_id NUMBER(6),
	prf_tpd_id NUMBER(6) NOT NULL, 
	prf_usu_id NUMBER(6) NOT NULL,

	CONSTRAINT PK_PREFERENCIAS PRIMARY KEY (prf_id),
	CONSTRAINT FK_PRF_USU FOREIGN KEY (prf_usu_id) REFERENCES USUARIOS (usu_id),
	CONSTRAINT FK_PRF_TPD FOREIGN KEY (prf_tpd_id) REFERENCES TIPOS_PRODUTO (tpd_id)
);

CREATE TABLE STATUS (
	sts_id NUMBER(6),
	sts_descricao VARCHAR2(20),
	
	CONSTRAINT PK_STATUS PRIMARY KEY (sts_id)
);

CREATE TABLE EMPRESTIMOS (
	emp_id NUMBER(6),
	emp_dt_inicio DATE, 
	emp_dt_final DATE, 
	emp_sts_id NUMBER(6), 
	emp_usu_id NUMBER(6),
	emp_exp_id NUMBER(6),

	CONSTRAINT PK_EMPRESTIMOS PRIMARY KEY (emp_id),
	CONSTRAINT FK_EMP_STS FOREIGN KEY (emp_sts_id) REFERENCES STATUS (sts_id),
	CONSTRAINT FK_EMP_USU FOREIGN KEY (emp_usu_id) REFERENCES USUARIOS (usu_id),
	CONSTRAINT FK_EMP_EXP FOREIGN KEY (emp_exp_id) REFERENCES EXEMPLARES (exp_id)
);