CREATE SEQUENCE SEQ_EST NOCACHE;
CREATE OR REPLACE TRIGGER TG_EST 
    BEFORE INSERT ON ESTADOS
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.EST_id := SEQ_EST.NEXTVAL;
END;

CREATE SEQUENCE SEQ_CID NOCACHE;
CREATE OR REPLACE TRIGGER TG_CID 
    BEFORE INSERT ON CIDADES
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.CID_id := SEQ_CID.NEXTVAL;
END;

CREATE SEQUENCE SEQ_END NOCACHE;
CREATE OR REPLACE TRIGGER TG_END 
    BEFORE INSERT ON ENDERECOS
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.END_id := SEQ_END.NEXTVAL;
END;

CREATE SEQUENCE SEQ_USU NOCACHE;
CREATE OR REPLACE TRIGGER TG_USU 
    BEFORE INSERT ON USUARIOS
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.USU_id := SEQ_USU.NEXTVAL;
END;

CREATE SEQUENCE SEQ_CNV NOCACHE;
CREATE OR REPLACE TRIGGER TG_CNV 
    BEFORE INSERT ON CONVERSAS
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.CNV_id := SEQ_CNV.NEXTVAL;
END;

CREATE SEQUENCE SEQ_MSG NOCACHE;
CREATE OR REPLACE TRIGGER TG_MSG 
    BEFORE INSERT ON MENSAGENS
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.MSG_id := SEQ_MSG.NEXTVAL;
END;

CREATE SEQUENCE SEQ_PRD NOCACHE;
CREATE OR REPLACE TRIGGER TG_PRD 
    BEFORE INSERT ON PRODUTOS
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.PRD_id := SEQ_PRD.NEXTVAL;
END;

CREATE SEQUENCE SEQ_EXP NOCACHE;
CREATE OR REPLACE TRIGGER TG_EXP 
    BEFORE INSERT ON EXEMPLARES
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.EXP_id := SEQ_EXP.NEXTVAL;
END;

CREATE SEQUENCE SEQ_TPD NOCACHE;
CREATE OR REPLACE TRIGGER TG_TPD 
    BEFORE INSERT ON TIPOS_PRODUTO
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.TPD_id := SEQ_TPD.NEXTVAL;
END;

CREATE SEQUENCE SEQ_PTP NOCACHE;
CREATE OR REPLACE TRIGGER TG_PTP 
    BEFORE INSERT ON PRODUTOS_TIPOS_PRODUTO
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.PTP_id := SEQ_PTP.NEXTVAL;
END;

CREATE SEQUENCE SEQ_PRF NOCACHE;
CREATE OR REPLACE TRIGGER TG_PRF 
    BEFORE INSERT ON PREFERENCIAS
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.PRF_id := SEQ_PRF.NEXTVAL;
END;

CREATE SEQUENCE SEQ_STS NOCACHE;
CREATE OR REPLACE TRIGGER TG_STS 
    BEFORE INSERT ON STATUS
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.STS_id := SEQ_STS.NEXTVAL;
END;

CREATE SEQUENCE SEQ_EMP NOCACHE;
CREATE OR REPLACE TRIGGER TG_EMP 
    BEFORE INSERT ON EMPRESTIMOS
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    :NEW.EMP_id := SEQ_EMP.NEXTVAL;
END;

