insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/06/2018', 'pulvinar lobortis est phasellus sit amet erat nulla', 63);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/07/2017', 'amet sem', 63);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/10/2018', 'et ultrices posuere cubilia curae nulla', 71);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/02/2017', 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', 72);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/03/2017', 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec', 97);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/01/2018', 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam', 79);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/09/2017', 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet', 45);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/06/2017', 'ipsum primis in', 25);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/09/2018', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede', 25);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/05/2017', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et', 85);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/01/2017', 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci', 56);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/09/2018', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis', 91);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/12/2017', 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', 16);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/11/2018', 'aliquam erat volutpat in congue etiam justo etiam', 89);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/07/2017', 'sapien ut nunc vestibulum ante ipsum primis in faucibus', 12);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/03/2018', 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet', 82);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/12/2017', 'venenatis turpis enim blandit mi in porttitor pede', 32);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/11/2017', 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus', 91);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/08/2017', 'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam', 13);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/04/2017', 'quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque', 70);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/04/2017', 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 84);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/01/2017', 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', 24);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/08/2018', 'diam in magna bibendum imperdiet nullam orci pede', 63);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/02/2017', 'ipsum dolor sit amet consectetuer adipiscing elit', 40);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/03/2017', 'volutpat eleifend donec ut dolor morbi vel', 57);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/12/2017', 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a', 26);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/08/2018', 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 28);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/07/2017', 'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel', 9);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/03/2018', 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 81);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/08/2017', 'dictumst etiam faucibus cursus urna', 77);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('14/06/2018', 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit', 82);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('23/06/2017', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', 25);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('14/10/2018', 'elementum eu interdum eu', 62);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/11/2017', 'ut dolor morbi vel lectus in', 8);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/10/2018', 'non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc', 80);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/08/2017', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum', 34);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/05/2017', 'rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 69);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/07/2017', 'volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui', 86);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/07/2018', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', 37);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/09/2017', 'arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium', 7);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/06/2018', 'nunc proin', 56);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/06/2017', 'hac habitasse platea dictumst maecenas ut massa quis augue luctus', 96);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/12/2017', 'molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer', 47);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/07/2018', 'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', 32);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/08/2017', 'sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris', 25);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/04/2018', 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', 26);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/07/2017', 'ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget', 66);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/05/2017', 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a', 56);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/06/2017', 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl', 21);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/06/2018', 'sit amet diam in magna bibendum imperdiet nullam', 29);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/04/2018', 'dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat', 3);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/10/2018', 'mus etiam vel augue vestibulum rutrum rutrum', 22);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/03/2017', 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt', 3);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/08/2018', 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in', 59);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/04/2018', 'maecenas tincidunt lacus at velit vivamus vel nulla', 25);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/02/2018', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in', 70);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/03/2018', 'mi sit amet lobortis', 61);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/11/2017', 'dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit', 69);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/12/2017', 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean', 3);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/02/2018', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 4);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/07/2018', 'in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla', 47);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/07/2018', 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', 95);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/08/2018', 'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', 12);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('23/04/2018', 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 13);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/10/2018', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id', 16);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/07/2017', 'neque duis bibendum morbi non quam nec dui luctus rutrum', 70);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/03/2018', 'eget eleifend luctus ultricies eu nibh quisque id justo sit amet', 69);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/02/2018', 'feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 56);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/02/2018', 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien', 4);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/05/2017', 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue', 46);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/04/2017', 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis', 84);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/10/2017', 'in sagittis dui vel nisl duis', 93);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/01/2017', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 64);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/06/2017', 'in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 16);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/09/2017', 'nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget', 29);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/06/2018', 'cubilia curae duis faucibus accumsan odio curabitur convallis duis', 86);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/03/2017', 'at nibh in hac habitasse platea dictumst aliquam augue quam', 52);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/08/2017', 'amet lobortis sapien sapien non mi integer ac', 84);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/11/2017', 'eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue', 57);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('04/05/2017', 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 33);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/03/2017', 'eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet', 79);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/12/2017', 'cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam', 62);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/01/2018', 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget', 74);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/10/2017', 'est lacinia nisi', 70);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/07/2017', 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat', 47);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/09/2017', 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim', 33);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/05/2018', 'nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus', 21);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/02/2017', 'eleifend pede libero quis orci nullam molestie nibh in lectus', 58);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('04/07/2018', 'adipiscing lorem vitae mattis nibh ligula', 7);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('10/09/2017', 'proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus', 82);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/08/2017', 'id ornare imperdiet sapien', 5);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/10/2017', 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in', 88);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/08/2018', 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit', 33);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/03/2017', 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi', 71);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/12/2017', 'vitae nisi nam ultrices libero non mattis pulvinar nulla', 22);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/01/2017', 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie', 92);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/10/2017', 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', 45);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('23/01/2018', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus', 59);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/10/2018', 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam', 30);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/12/2017', 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', 55);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/01/2017', 'risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', 84);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/05/2017', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis', 36);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/02/2017', 'non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus', 47);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/09/2018', 'ultrices posuere cubilia curae mauris', 69);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/06/2017', 'laoreet ut rhoncus aliquet pulvinar sed nisl', 60);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/08/2017', 'amet erat nulla', 85);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/04/2018', 'ornare imperdiet sapien urna', 80);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/10/2018', 'consequat nulla nisl nunc nisl duis bibendum', 12);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/10/2018', 'augue a suscipit nulla', 91);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/10/2018', 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus', 76);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/03/2017', 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras', 71);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('19/08/2017', 'ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper', 9);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('23/06/2017', 'ante ipsum primis in faucibus orci luctus et ultrices', 7);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/08/2017', 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu', 49);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/05/2017', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci', 88);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('10/10/2017', 'eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum', 90);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/01/2018', 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam', 79);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/05/2017', 'risus semper porta', 58);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('23/02/2017', 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer', 21);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/05/2017', 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed', 79);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/04/2017', 'nulla elit ac nulla sed vel enim sit amet nunc viverra', 20);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/01/2018', 'nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus', 99);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/03/2018', 'cras non velit nec nisi vulputate nonummy', 17);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/05/2017', 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis', 11);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/06/2018', 'consequat nulla nisl', 51);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/02/2017', 'turpis nec euismod', 66);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/06/2018', 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie', 58);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/09/2017', 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh', 19);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/01/2018', 'consequat dui nec nisi volutpat eleifend donec ut', 58);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/04/2017', 'leo rhoncus sed vestibulum sit amet', 81);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('03/05/2017', 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', 81);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/05/2017', 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', 43);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/02/2018', 'ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat', 18);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/05/2017', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', 47);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/11/2018', 'luctus et ultrices posuere cubilia', 3);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/09/2018', 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', 46);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/07/2017', 'condimentum curabitur in libero ut massa volutpat convallis morbi odio odio', 81);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/11/2017', 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi', 12);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/06/2018', 'platea dictumst morbi vestibulum', 36);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/08/2018', 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 3);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/02/2017', 'et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', 74);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/01/2017', 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi', 17);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/07/2017', 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor', 49);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/08/2018', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst', 18);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/07/2018', 'mauris vulputate', 32);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/11/2018', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', 10);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/05/2017', 'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna', 28);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/04/2018', 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque', 50);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/09/2017', 'purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam', 99);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/04/2018', 'magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 14);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/03/2018', 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec', 79);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/04/2018', 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis', 38);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/05/2017', 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum', 66);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/03/2018', 'nisi venenatis tristique fusce congue', 45);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/07/2018', 'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas', 46);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/12/2017', 'augue vestibulum rutrum rutrum neque aenean auctor', 66);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/08/2017', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum', 81);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/06/2018', 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede', 55);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/05/2018', 'eu interdum eu', 9);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/02/2018', 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus', 35);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/05/2018', 'eleifend luctus ultricies eu nibh quisque id justo', 60);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/06/2018', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis', 25);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/12/2017', 'nunc viverra dapibus nulla suscipit ligula in lacus', 92);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/06/2017', 'adipiscing elit proin risus', 23);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/07/2018', 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis', 100);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/01/2018', 'augue aliquam erat volutpat in', 69);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/08/2018', 'elit proin risus praesent lectus vestibulum quam sapien', 52);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/08/2018', 'odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', 34);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/01/2018', 'massa volutpat convallis morbi odio', 33);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('19/05/2018', 'quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse', 42);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/03/2018', 'turpis enim blandit mi in porttitor pede', 96);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/07/2018', 'id ligula', 12);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/07/2018', 'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 24);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('14/03/2017', 'varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi', 74);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/08/2018', 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor', 74);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('03/10/2018', 'accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla', 31);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('10/07/2017', 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum', 55);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/04/2017', 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus', 69);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/11/2017', 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti', 10);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/12/2017', 'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel', 27);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('04/03/2018', 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec', 32);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/03/2017', 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis', 51);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('23/09/2017', 'consequat morbi a ipsum integer a nibh in', 26);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/04/2018', 'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla', 29);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/04/2018', 'eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla', 84);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/10/2018', 'non mauris morbi', 21);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/03/2017', 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue', 96);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/08/2017', 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 54);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/09/2018', 'posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum', 64);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/08/2018', 'velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', 47);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('19/01/2017', 'donec dapibus duis at velit eu', 38);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/06/2018', 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 63);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/09/2017', 'non velit donec diam neque vestibulum eget vulputate ut ultrices', 73);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/12/2017', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', 96);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/09/2017', 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam', 17);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/11/2018', 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 1);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/10/2018', 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet', 64);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/06/2017', 'condimentum id luctus nec molestie sed justo', 75);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('03/03/2018', 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 71);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/10/2018', 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus', 5);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/05/2018', 'eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 19);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/02/2017', 'sed tristique in tempus sit amet', 42);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/08/2017', 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a', 34);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/10/2017', 'dolor quis odio consequat varius integer ac leo', 90);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/03/2018', 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis', 31);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/12/2017', 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis', 32);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/08/2017', 'posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est', 81);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/11/2018', 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', 47);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/11/2018', 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 97);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/03/2017', 'risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis', 69);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/04/2018', 'in consequat ut nulla sed accumsan felis ut at', 38);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/11/2017', 'quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien', 81);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/08/2018', 'ante ipsum primis in faucibus orci', 62);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/05/2018', 'etiam faucibus cursus urna', 32);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/09/2018', 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere', 33);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/10/2018', 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', 83);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('23/02/2018', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida', 64);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/11/2018', 'praesent blandit lacinia erat vestibulum sed', 53);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/11/2017', 'quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 2);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/10/2017', 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut', 10);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/11/2018', 'at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam', 62);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/01/2017', 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis', 51);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/06/2018', 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl', 52);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/01/2017', 'montes nascetur ridiculus mus etiam vel augue vestibulum', 92);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/03/2017', 'faucibus cursus urna ut tellus nulla', 90);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/08/2018', 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', 99);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/09/2017', 'amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at', 21);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('23/07/2018', 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', 44);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/05/2017', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', 23);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/01/2018', 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis', 10);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('10/07/2018', 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 69);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/01/2018', 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in', 75);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/08/2018', 'donec pharetra magna', 57);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/02/2018', 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi', 10);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/03/2017', 'nunc rhoncus dui vel sem sed sagittis nam congue risus semper', 64);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/10/2017', 'aliquam sit amet', 75);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('14/12/2017', 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 72);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('04/04/2017', 'adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy', 12);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/03/2017', 'placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 3);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/03/2017', 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 25);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/05/2017', 'pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae', 95);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('04/02/2017', 'pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', 56);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/01/2017', 'pellentesque quisque', 52);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/09/2017', 'eu massa donec dapibus duis at velit eu est congue elementum in', 52);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('14/11/2018', 'sit amet eleifend pede libero quis orci nullam molestie', 54);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('10/10/2018', 'nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros', 78);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/01/2017', 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque', 60);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/12/2017', 'rhoncus aliquam lacus morbi', 86);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/04/2017', 'eu nibh quisque id justo sit amet sapien dignissim vestibulum', 23);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/07/2017', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat', 36);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/08/2017', 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget', 33);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/08/2017', 'vestibulum sagittis sapien cum', 58);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/10/2017', 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras', 41);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/08/2017', 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', 100);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/08/2018', 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed', 99);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/07/2017', 'at nibh in hac habitasse platea dictumst aliquam', 59);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/10/2018', 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla', 46);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/07/2018', 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper', 92);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/01/2018', 'eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', 92);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/07/2017', 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl', 2);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/10/2017', 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 6);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/09/2018', 'lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', 18);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/04/2018', 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing', 58);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/10/2018', 'vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas', 15);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/03/2018', 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', 68);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/11/2018', 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', 2);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/10/2017', 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis', 25);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/09/2017', 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa', 9);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/04/2018', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque', 85);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/11/2017', 'lectus pellentesque eget nunc donec quis orci eget orci', 57);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/01/2017', 'turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis', 85);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/08/2017', 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam', 93);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/05/2018', 'sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in', 91);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/02/2018', 'diam vitae quam suspendisse potenti nullam porttitor lacus', 18);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/08/2018', 'cum sociis natoque penatibus et magnis dis parturient montes nascetur', 81);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('14/02/2017', 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 8);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/07/2018', 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', 96);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/11/2017', 'at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum', 49);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/06/2018', 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer', 54);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('14/07/2018', 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum', 30);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/03/2017', 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci', 66);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/09/2018', 'ullamcorper augue a suscipit nulla elit ac nulla sed vel', 64);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/10/2018', 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque', 73);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/07/2017', 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 26);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/11/2017', 'morbi odio odio elementum eu', 63);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/03/2017', 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus', 95);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/08/2018', 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat', 88);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('19/02/2017', 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget', 92);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/04/2017', 'quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a', 90);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('14/03/2018', 'interdum mauris non ligula pellentesque', 10);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/06/2017', 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede', 91);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/03/2018', 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 78);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/08/2018', 'turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas', 33);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/11/2017', 'augue vel', 23);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/02/2018', 'nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi', 68);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/09/2018', 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis', 34);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/03/2017', 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', 30);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/01/2018', 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae', 64);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/01/2018', 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim', 51);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/08/2018', 'libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', 69);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/06/2017', 'nam congue risus semper porta volutpat quam pede lobortis ligula sit amet', 10);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/03/2018', 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 67);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/11/2017', 'tincidunt eget', 2);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/06/2017', 'tempor convallis nulla neque', 45);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/02/2017', 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 51);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/03/2017', 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla', 99);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/08/2018', 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', 36);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/12/2017', 'quis turpis', 65);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/04/2017', 'lobortis sapien sapien non mi integer ac neque duis bibendum morbi non', 70);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('10/09/2017', 'vestibulum ante ipsum primis in faucibus', 36);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/06/2017', 'molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat', 44);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('25/09/2018', 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor', 37);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/06/2018', 'diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', 69);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/05/2017', 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante', 57);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('19/10/2018', 'metus sapien ut nunc vestibulum ante', 36);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/10/2018', 'ultrices posuere cubilia curae', 83);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/05/2018', 'magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut', 33);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/06/2017', 'felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis', 17);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/09/2018', 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in', 11);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('20/08/2017', 'in faucibus orci luctus et ultrices', 75);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('23/04/2017', 'amet cursus id turpis integer', 31);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/08/2018', 'nulla elit', 36);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/05/2018', 'egestas metus aenean fermentum', 95);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/05/2018', 'nam nulla integer', 4);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/04/2018', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 71);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('03/11/2018', 'eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida', 93);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('19/09/2018', 'ac tellus semper interdum mauris ullamcorper purus sit amet nulla', 62);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/06/2017', 'eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 100);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/03/2017', 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante', 90);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/10/2017', 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 82);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/09/2018', 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt', 75);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/10/2018', 'sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper', 11);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('19/03/2017', 'est quam pharetra magna ac consequat', 28);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('10/02/2018', 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus', 91);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/04/2018', 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', 86);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/06/2018', 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', 34);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/09/2017', 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et', 13);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('14/04/2017', 'id ligula suspendisse', 98);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/05/2018', 'pede morbi porttitor', 75);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/06/2018', 'vel sem sed sagittis nam congue risus semper porta volutpat', 14);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/07/2018', 'nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam', 72);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('19/06/2018', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum', 93);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/02/2017', 'lobortis ligula sit amet eleifend pede libero quis', 45);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/11/2017', 'interdum mauris ullamcorper purus sit amet nulla', 90);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/05/2017', 'aliquet pulvinar sed nisl', 89);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/09/2018', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus', 15);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/11/2018', 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius', 17);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/06/2017', 'in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet', 6);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('04/06/2018', 'non mauris morbi non lectus aliquam sit', 24);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('02/04/2018', 'pede justo lacinia', 8);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('12/01/2017', 'nulla facilisi cras non', 49);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/07/2017', 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed', 32);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/07/2018', 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum', 9);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/05/2018', 'non pretium quis', 79);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/10/2017', 'consectetuer eget rutrum at lorem integer tincidunt', 64);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('11/08/2017', 'quis justo maecenas rhoncus aliquam lacus morbi quis', 41);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('21/04/2018', 'lorem ipsum dolor sit amet consectetuer adipiscing elit', 46);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/02/2018', 'in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', 31);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/11/2018', 'sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis', 57);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/09/2017', 'in purus eu magna vulputate luctus cum sociis natoque penatibus et', 3);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/06/2017', 'molestie nibh in lectus pellentesque at nulla suspendisse potenti', 36);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('04/07/2017', 'rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non', 54);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/03/2018', 'proin risus praesent lectus vestibulum quam sapien varius ut blandit non', 76);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('13/03/2017', 'et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', 93);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/11/2018', 'non mattis', 60);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('17/02/2018', 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu', 54);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/08/2017', 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras', 29);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/03/2018', 'placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor', 41);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/06/2017', 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean', 16);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/05/2018', 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede', 30);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('07/07/2018', 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam', 11);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/07/2018', 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit', 79);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/01/2018', 'proin leo odio', 42);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('08/01/2017', 'semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 87);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('26/04/2017', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est', 50);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/10/2017', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor', 12);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/01/2017', 'sed tincidunt eu felis fusce posuere felis sed', 94);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('30/06/2017', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 40);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/09/2017', 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 8);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/03/2017', 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 41);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('16/11/2018', 'semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', 48);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('01/04/2018', 'diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec', 73);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/01/2018', 'ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 23);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('28/04/2018', 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas', 95);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/04/2017', 'nisi volutpat', 29);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/03/2017', 'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', 78);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('04/06/2018', 'ac neque duis bibendum morbi non quam nec dui luctus rutrum', 4);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('06/03/2017', 'pretium nisl ut volutpat sapien arcu', 73);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('31/10/2018', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', 99);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('24/05/2018', 'imperdiet nullam orci', 43);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('19/09/2018', 'euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis', 44);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('19/11/2017', 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu', 6);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('05/05/2017', 'consequat metus sapien ut', 61);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('04/12/2017', 'odio odio elementum eu interdum', 65);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('09/08/2017', 'diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt', 87);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('15/11/2017', 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis', 43);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('27/05/2018', 'eget tempus vel pede', 76);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('18/01/2018', 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', 48);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('29/06/2017', 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis', 76);
insert into MENSAGENS (msg_data, msg_conteudo, msg_cnv_id) values ('22/10/2018', 'at ipsum ac tellus semper interdum mauris', 24);
