insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Lunder', '06525', '16416863', 'Pau Ferrado', 2920);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Mesta', '715', '69823140', 'Alto Da Fé (Padre Cicero)', 249);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Stuart', '04449', '80393658', 'Chacara Petropolis', 5459);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Morningstar', '3741', '29811925', 'Zona Urbana (Jaqueira)', 2700);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Farwell', '7894', '72190379', 'Area Candeias', 651);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Oak Valley', '0591', '83372601', 'Vila Dois Leoes', 2815);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Mcguire', '0504', '12244434', 'Furnas Das Pacas', 448);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Thompson', '35776', '74139260', 'Casa Forte', 1659);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Elmside', '6', '76282468', 'Entroncamento', 2358);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Coolidge', '7', '95676646', 'Belém', 5551);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Gulseth', null, '29508372', 'Estancia', 3099);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Mosinee', '2653', '03321153', 'Sitio Montado De Baixo (Zona Urbana)', 2493);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Bartelt', '28', '55343306', 'Area Candeias', 2030);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Glacier Hill', '67304', '72023018', 'Areia Branca', 1218);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Lien', '43', '94419640', 'Vila Boa Esperança', 2991);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Bluejay', '03459', '70310232', 'Amparo', 61);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Badeau', '5754', '49016004', 'Riacho Do Navio', 5056);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Forster', null, '31017347', 'Engenho Furnas', 4959);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Riverside', '786', '24796429', 'Parnamirim', 1012);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Westerfield', '9652', '37315232', 'Cosme E Damião', 3022);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Division', '0', '96471369', 'Loteamento Esperança', 4271);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Kropf', null, '78010425', 'Cohab (São Vicente Férrer)', 3207);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Morning', '92', '79966964', 'Boa  Vista', 1225);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Hovde', '96404', '11750108', 'Bairro Dos Estados', 4605);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Southridge', null, '95411979', 'Alto Jose Leite', 5433);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Artisan', '7', '39310371', 'Lot Ana Albuquerque', 5270);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Valley Edge', null, '11436338', 'Alto Por Do Sol', 4554);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Messerschmidt', '3747', '57681401', 'Engenho Canto Flor', 5442);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Pepper Wood', '50347', '58608469', 'Ouro Preto', 675);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Muir', '8', '24480113', 'Serra De Capoeira(Zona Rural)', 3078);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Butternut', null, '51288773', 'Sitio Baixa De Oratório (Zona Urbana)', 3944);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Springview', '14', '94980756', 'Cidade Baixa', 3964);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Reinke', '7', '31410128', 'Engenho Flor De Maria', 1197);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Thackeray', null, '08239493', 'Pitanga I', 1787);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Golden Leaf', '22113', '42709123', 'Engenho Aripou  (Zona Rural)', 497);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Ronald Regan', '45', '01337494', 'Abc', 2300);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('West', '735', '66898548', 'Alto Jose Bonifacio', 3911);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Moose', '8', '18630803', 'Alto Da Liberdade', 1684);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Manitowish', '04356', '25028419', 'Furnas Das Pacas', 1331);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Tennyson', '26', '68370744', 'Vila Bom Sucesso', 4900);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Blue Bill Park', '77440', '47762600', 'Centro', 1861);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Raven', '401', '63249450', 'Lot Caicara Iii', 532);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Service', null, '03755761', 'Cohab', 2949);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Sommers', '330', '39241669', 'Lot Conceição- Iraque', 4642);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Oakridge', '0698', '80244643', 'Sitio Baixa De Oratório (Zona Urbana)', 1480);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Londonderry', '9', '43151444', 'Caetes Velho', 5341);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Kennedy', null, '44838797', 'Lot Sao Severino', 786);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Carioca', '94132', '33542335', 'Residencial Lucia De Fatima Ii', 3500);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Northview', '708', '99493880', 'Engenho Canoinha', 2076);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Mallard', null, '25347911', 'Engenho Cachoeira Dantas', 2366);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Melvin', '72', '47797654', 'Bela Vista', 3066);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Gale', '1352', '86121618', 'Centro', 3807);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Melby', '48918', '72982575', 'Engenho Bom Conselho', 4744);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Drewry', '466', '37119965', 'Espalhagua', 503);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Fieldstone', '1', '51444754', 'Centro', 2000);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('7th', '64714', '40314985', 'Comportas', 154);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Pankratz', '6', '64716566', 'Paratibe', 3982);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Dennis', '80832', '68366084', 'Vasconcelos', 591);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Oakridge', '3401', '19245425', 'Area Tamanduá', 70);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Iowa', '84', '47079021', 'Loteamento Santo Antonio', 93);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Spenser', '97058', '09565519', 'Asa Branca', 1857);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Dixon', '8853', '19469515', 'Maria Farinha', 2049);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Kingsford', '9', '06308065', 'Vila Prof Lucia Fatima Galindo(Salgadeir', 5052);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Basil', '32', '78190051', 'Jatobá', 805);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Oak Valley', '4', '03444064', 'Nova Escada', 547);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Ruskin', '1098', '64397907', 'Caetes Velho', 4893);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('6th', '83797', '17665585', 'Sitio Cha De Laço (Zona Urbana)', 4303);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Marquette', null, '92688782', 'Engenho Limão', 20);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Bashford', '4', '95358379', 'Jacaré', 3223);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Lakeland', '4', '91584291', 'Engenho  Capim-Acu', 1282);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Wayridge', '5689', '28452697', 'Alto Da Bela Vista', 3384);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Golf Course', '2721', '64650443', 'Alaíde Gonçalves', 1911);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Elmside', '8', '68800684', 'Saco De Cobras', 2660);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Donald', '0', '03678454', 'Vila Cenira', 2786);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Nova', '8', '86019225', 'Olho D''agua De Baixo', 4024);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Upham', '3', '15154930', 'Engenho Lajedo', 4742);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Oak Valley', '136', '41208378', 'Visgueiro', 583);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Green', '65', '75218322', 'Engenho Humaitá', 2248);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Grim', '2655', '20536776', 'Jagata', 3217);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Bunting', '8', '75489496', 'Novo Horizonte', 3365);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Miller', '0153', '73904274', 'Engenho Teimoso', 2261);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('8th', '8', '12701263', 'Poco Da Panela', 1223);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Crescent Oaks', '35378', '65380163', 'Campo Do Sete', 4924);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Sauthoff', '2845', '42623980', 'Vila Dois Leoes', 3269);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Emmet', '82', '91299140', 'Vila São Marcos', 3938);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Old Gate', '49287', '49765322', 'Engenho Cabaruna', 809);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Marquette', '6095', '94007729', 'Area Ribeiro Do Mel', 3360);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Rusk', '59323', '72222645', 'Timbi( Acude/ Sao Francisco)', 3285);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('New Castle', '769', '43477351', 'Alto Neco De Leu', 1177);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Loftsgordon', '7952', '19213047', 'Sitio Dois Irmãos', 1755);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Hauk', '63', '72152472', 'Engenho Cavada', 5370);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Schlimgen', '83338', '59357203', 'Toto', 1857);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Meadow Ridge', '232', '29592374', 'Progresso', 179);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Prentice', '00', '08691901', 'Engenho Macacos', 4981);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Banding', '8', '39055633', 'Munguba', 3352);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Talisman', '0293', '21593754', 'Loteamento Engenho Figueredo', 4645);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Derek', '39185', '18174853', 'Centro', 34);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Fairfield', '917', '33083213', 'Santa Rita', 4566);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Northridge', '86041', '36270897', 'Barra De Lama', 4713);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Moulton', '4212', '85737376', 'Constantino Maranhao(Bonanca)', 4498);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Corry', '05300', '74565067', 'Alto Jose Do Pinho', 3872);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Johnson', '661', '91806116', 'Entroncamento', 1631);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('6th', '47', '93184264', 'Tambor', 4451);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Darwin', null, '16803981', 'Diogo', 3767);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Spohn', '5047', '46932841', 'Centro (Paudalho)', 1878);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Southridge', '44114', '06210418', 'Engenho Florente', 2938);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Onsgard', '18', '38769318', 'Engenho Fernando Vieira', 4569);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Maryland', '25371', '49119604', 'Pitanga Ii', 4163);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Vermont', '5', '31408549', 'Nossa Senhora Do Ó', 764);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Golden Leaf', null, '85990515', 'Manoel Aprígio', 3693);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Hintze', '50', '51648643', 'Engenho Arial', 3805);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Lawn', '08359', '66397420', 'Ines', 478);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Mayfield', '90963', '38841279', 'Pau Ferro', 1573);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Anhalt', '7', '75617025', 'Esperanca', 2356);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('North', '33048', '68699606', 'Planalto', 3427);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Moulton', '37527', '31305336', 'Engenho Cumbre De Cima', 4632);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Harper', '5', '71039795', 'Vila Agrovila', 1105);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Coleman', '641', '40718115', 'São José', 2343);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Village', null, '71813254', 'São Sebastião', 1644);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Dottie', '63092', '76325962', 'Ladeira De Pedra', 2835);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Homewood', '0690', '04665960', 'Ladeira De Pedra', 3096);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Kedzie', '766', '13192207', 'Forte Orange', 1064);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Memorial', '6', '38636253', 'Canaa', 840);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Moose', '85106', '85054453', 'Abc', 1884);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Sundown', '6771', '71078829', 'Engenho Lage Nova (Zona Rural)', 1585);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Golf Course', '748', '48819985', 'Bela Vista', 3915);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Heffernan', '9', '41643375', 'Engenho Paraná', 1017);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Hoard', '5402', '02542617', 'Ladeira Cavada', 285);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Schlimgen', '45444', '33599139', 'Cruz De Rebouças', 1734);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Forest', '35', '42806271', 'Centro', 764);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Oxford', '530', '65110242', 'Marcelo De Juquinha', 5248);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Clyde Gallagher', '24', '31899070', 'Bulandi', 31);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Coolidge', '536', '62653156', 'Area Poço Do Pau', 1338);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Briar Crest', '65', '01283239', 'Umuarana', 4455);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Farwell', '366', '38525861', 'Zona Rural', 562);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Bowman', '902', '35872956', 'Campo Grande (Zona Rural)', 994);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Stoughton', '68592', '88835192', 'Centro', 2877);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Corscot', '5', '30057163', 'Vila Santa Monica', 50);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('6th', '91', '79713627', 'Area Olho D''agua De Figueiras', 3724);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Continental', '36240', '42638729', 'Bobocão', 2933);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Ramsey', '146', '40620460', 'Prive Vermont', 5205);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Basil', '0', '46005853', 'Engenho Aripou  (Zona Rural)', 2558);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Buell', '4', '40581812', 'Ignorado', 1605);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Homewood', '77797', '17167732', 'Alto Da Mina', 3044);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Michigan', '7808', '77548074', 'Tanques', 422);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Dryden', '4737', '70912409', 'Campo Grande (Zona Rural)', 5360);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Nelson', null, '30319791', 'Engenho Fundao', 2916);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Mallory', '960', '82454876', 'Fazenda Vale Do Una', 1164);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Talisman', null, '36210855', 'Engenho Cachoeira Dantas', 3073);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('David', '61369', '48225279', 'Sitio Novo', 2877);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('South', '45898', '66838913', 'Liberdade', 3933);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Northwestern', '0', '81272715', 'Centro', 1696);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Lotheville', '337', '60607997', 'Gurjau', 3230);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('1st', '55209', '40939121', 'Engenho Siriquita', 471);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Esker', '8', '56965889', 'Quinze', 2302);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Hagan', null, '04911554', 'Lagoa De Flexa', 5342);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Southridge', '98', '18204356', 'Santa Izabel', 4167);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Columbus', '398', '21901336', 'Engenho Cruz De Malta', 4397);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Haas', '7568', '90301037', 'Engenho Poço', 4472);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Farragut', '391', '34342640', 'Vila Frexeiras', 169);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Maywood', '46601', '29447868', 'Ilha Do Retiro', 1905);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Pawling', '7079', '56458324', 'Engenho Balsamo Das Freiras (Zona Rural)', 677);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Fairview', '99943', '16715584', 'Lot Belo Horizonte Malv', 577);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Morning', '6955', '27075699', 'Alto Da Capela', 121);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('8th', '4817', '63202393', 'Vila Do Boldró', 4863);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Schlimgen', '2', '31740958', 'Distrito De Quebeque', 2242);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Superior', '4', '42224982', 'Engenho Cumaru', 55);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Grayhawk', '396', '33535570', 'Toto', 3741);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Cody', '92', '48999614', 'Area Bengalas', 1178);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Rutledge', '692', '58929596', 'Guabiraba', 2916);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Roth', '7825', '74276077', 'Campina Do Barreto', 1949);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Amoth', '295', '29112947', 'Gravata', 3358);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Oakridge', '5533', '39519805', 'Morro Da Conceicao', 4970);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Roth', '1', '47072377', 'Sapucaia De Dentro', 864);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Nancy', '516', '52442484', 'Salto', 788);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Sheridan', '8116', '94895174', 'Varzea', 2569);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Fairfield', '484', '70037764', 'Varzea Do Inga', 1867);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Daystar', '97013', '85548566', 'Matadouro', 1295);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Briar Crest', '281', '22693391', 'Centro (Camutanga)', 4709);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Mockingbird', '605', '68023735', 'Sitio Dos Pintos', 91);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Rieder', '144', '01018825', 'Corrego Do Desastre', 3681);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Monument', '3737', '31601460', 'Cacote', 2620);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Montana', '73530', '36690447', 'Celeiro', 4366);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Lerdahl', '582', '35669045', 'Engenho Vista Alegre', 4838);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Brown', '1431', '90038070', 'Sitio Grande (Zona Rural)', 3542);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Bobwhite', '2', '53468376', 'Centro', 858);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Jana', '17887', '91425349', 'Sitio Salgado', 510);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Glacier Hill', '09', '89424825', 'Centro', 5024);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Banding', '694', '32097159', 'Bom Jardim', 3305);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Colorado', '81', '17748066', 'Passo Comprido', 2981);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Golf View', '59', '76796333', 'Centro (São Vicente Férrer)', 4336);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Thierer', '26368', '55485338', 'Dois Carneiros', 4783);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Mccormick', '4', '34596525', 'Sitio Lagoa De Porco (Zona Urbana)', 1400);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Tennessee', '6919', '88214183', 'Cruangi (Zona Rural)', 1355);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Vernon', '42536', '09025970', 'Engenho Pastinho', 1676);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Buell', '9208', '11348400', 'Padre Ângelo (Projetada)', 2361);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Rockefeller', '0', '22505133', 'Inhama', 3996);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Oneill', '3', '41818236', 'Pirituba', 636);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Gerald', '45312', '79088713', 'Engenho Covas', 21);
insert into ENDERECOS (end_logradouro, end_numero, end_cep, end_bairro, end_cid_id) values ('Mockingbird', '0670', '36427337', 'Canafístula', 5110);
